---
- name: Install prerequisite packages
  become: true
  ansible.builtin.apt:
    name: ['acl', 'apt-transport-https', 'locales', 'python3-psycopg2']
    state: present
    update_cache: true

- name: Ensure UTF-8 locale exists
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Install postgres packages
  become: true
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
    state: present
    update_cache: true
    cache_valid_time: 3600
  register: download_postgresql
  until: download_postgresql is success
  retries: 3
  delay: 3
