---
- name: Manage prerequisite packages
  become: true
  ansible.builtin.apt:
    name: ['acl', 'apt-transport-https', 'locales', 'python3-psycopg2']
    state: "{{ desired_state }}"
    update_cache: true

- name: Ensure UTF-8 locale exists
  when: desired_state == 'present'
  become: true
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Manage postgres packages
  become: true
  ansible.builtin.apt:
    name:
      - postgresql
      - postgresql-contrib
    state: "{{ desired_state }}"
    update_cache: true
    cache_valid_time: 3600
  register: manage_postgresql
  until: manage_postgresql is success
  retries: 3
  delay: 3
